ADB:
  MODE: USB
  RETRIES: 1
  SID: 0123456789ABCDEF
CMD_TIMEOUT: 60
CONNECT: UART
Logging:
  Path: log_files
SN: 281818010518D000118QN276-0301181111U
TestBench:
  PreTest:
    Path: test_lists\pre_test.yml
UART:
  BAUD: 115200
  COM: COM4
  DUT_MAC: 8d81692291b0
  RETRIES: 2
  TIMEOUT: 1
